### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by berat639** [wassimmallehwm/react-semantic-ui-datatable#1]
``Hello there,
I started trying your library, I'm glad it's a work around because its examples are too few for semantic-ui. I noticed that pagination is not working when using your library. What could be the reason for this situation?

**Comment by berat639** [comment]
`import React from "react";  
import { Datatable } from 'react-semantic-ui-datatable';
import { Modal, Button } from 'semantic-ui-react' 
class Users extends React.Component {
    constructor(props){
      super(props) 
      this.state = { 
        datasource:  [
          {
            "_id": "1",
            "label": "Berat",
            "createdAt": "2021-05-31",
          },
          {
            "_id": "2",
            "label": "Shirt",
            "createdAt": "2021-05-31",
          },
          {
            "_id": "3",
            "label": "Samsung Galaxy S9",
            "createdAt": "2021-06-03"
          },
          {
            "_id": "4",
            "label": "Galaxy s10",
            "createdAt": "2021-06-03"
          },
          {
            "_id": "5",
            "label": "s11",
            "createdAt": "2021-06-03"
          },
          {
            "_id": "6",
            "label": "s12",
            "createdAt": "2021-06-03"
          },
          {
            "_id": "7",
            "label": "s13",
            "createdAt": "2021-06-03"
          },
          {
            "_id": "8",
            "label": "s14",
            "createdAt": "2021-06-03"
          },
          {
            "_id": "9",
            "label": "s11",
            "createdAt": "2021-06-03"
          },
          {
            "_id": "10",
            "label": "s15",
            "createdAt": "2021-06-03"
          },
          {
            "_id": "11",
            "label": "s16",
            "createdAt": "2021-06-03"
          }
        ]
      };
    }
    initialData=(data) => { 
      //initData
      //console.log(data);
      const datasource2 =  [
        {
          "_id": "1",
          "label": "Berat",
          "createdAt": "2021-05-31",
        },
        {
          "_id": "2",
          "label": "Shirt",
          "createdAt": "2021-05-31",
        },
        {
          "_id": "3",
          "label": "Samsung Galaxy S9",
          "createdAt": "2021-06-03"
        },
        {
          "_id": "4",
          "label": "Galaxy s10",
          "createdAt": "2021-06-03"
        },
        {
          "_id": "5",
          "label": "s11",
          "createdAt": "2021-06-03"
        },
        {
          "_id": "6",
          "label": "s12",
          "createdAt": "2021-06-03"
        },
        {
          "_id": "7",
          "label": "s13",
          "createdAt": "2021-06-03"
        },
        {
          "_id": "8",
          "label": "s14",
          "createdAt": "2021-06-03"
        },
        {
          "_id": "9",
          "label": "s11",
          "createdAt": "2021-06-03"
        },
        {
          "_id": "10",
          "label": "s15",
          "createdAt": "2021-06-03"
        },
        {
          "_id": "11",
          "label": "s16",
          "createdAt": "2021-06-03"
        }
      ]
      this.setState({
        datasource:datasource2
      })
    }
    refreshData=() => { 
      //refresh
      const datasource2 = [
        {
          "_id": "1",
          "label": "Berat",
          "createdAt": "2021-05-31",
        },
        {
          "_id": "2",
          "label": "Shirt",
          "createdAt": "2021-05-31",
        },
        {
          "_id": "3",
          "label": "Samsung Galaxy S9",
          "createdAt": "2021-06-03"
        },
        {
          "_id": "4",
          "label": "Galaxy s10",
          "createdAt": "2021-06-03"
        },
        {
          "_id": "5",
          "label": "s11",
          "createdAt": "2021-06-03"
        },
        {
          "_id": "6",
          "label": "s12",
          "createdAt": "2021-06-03"
        },
        {
          "_id": "7",
          "label": "s13",
          "createdAt": "2021-06-03"
        },
        {
          "_id": "8",
          "label": "s14",
          "createdAt": "2021-06-03"
        },
        {
          "_id": "9",
          "label": "s11",
          "createdAt": "2021-06-03"
        },
        {
          "_id": "10",
          "label": "s15",
          "createdAt": "2021-06-03"
        },
        {
          "_id": "11",
          "label": "s16",
          "createdAt": "2021-06-03"
        }
      ]
      this.setState({
        datasource:datasource2
      })
    }
    redirectEditUser=(id) => { 
      this.props.history.push(/UserEdit/${id})
    }
    deleteUser=(id) => { 
      console.log(id);
      this.refreshData();
    }
    render() {
      
     
      const colDefs = [
        {
          headerName: 'Label',
          field: 'label',
          sortable: true,
          filter: true
        },
        {
          headerName: 'Created at',
          field: 'createdAt',
          customRender: true,
          sortable: true,
          filter: true,
          filterOptions: {
            type: 'date'
          },
          cellRender: (data) => {
            return (
              data.createdAt
            )
          }
        },
        {
          headerName: 'Actions',
          field: 'actions',
          className: 'actions-cell',
          customRender: true,
          style: {
            minWidth: "120px",
            textAlign: 'center'
          },
          cellRender: (data) => {
            return (
              <>
                <Button className="action-btn" onClick={() => this.redirectEditUser(data._id)} circular primary icon='edit' />
                <Modal trigger={ <Button className="action-btn" circular negative icon='trash' />} header='Reminder!' content={`${data.label} silmek istediğinizden emin misiniz?`} actions={['İptal', { key: 'done', content: 'Done', positive: true, onClick:() => this.deleteUser(data._id)}]} /> 
               
              </>
            )
          }
        }
      ] 
        return (
      <div className="container-fluid"> 
                <div className="row">
        
                    <div className="col-xl-12 col-lg-12">
                                    <div className="card shadow mb-4"> 
                                      
                                        <div className="card-body">
                                            <h1>Users</h1>
                                            <Datatable sortable paginated columns={colDefs} datasource={this.state.datasource} serverSide onQueryChange={this.initialData}/>
                                            <Button content='Next' icon='right arrow' onClick={this.refreshData}/> 
                                        </div>
                                    </div>
                                </div>
                    </div>
             </div> 
        );
    }
}

export default Users;`

**Comment by wassimmallehwm** [comment]
Hello,
Since your datasource is static and you are not loading it from the server, you should remove **serverSide**  and **onQueryChange** attributes and it should work.
